apiVersion: batch/v1
kind: Job
metadata:
  name: kedro-etl-pipeline-job-reduced-lar-reports-parquet-2025
  namespace: cron-jobs
  labels:
    job: kedro-etl-pipeline-job-reduced-lar-reports-parquet-2025
spec:
  template:
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: kedro
          image: ECR-ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/cfpb/regtech/hmda/hmda-kedro-etl-pipeline:06082026-v1
          imagePullPolicy: Always
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: KEDRO_ENV
              value: dev
            - name: SQLALCHEMY_SILENCE_UBER_WARNING
              value: "1"
            - name: DO_NOT_TRACK
              value: "1"
          volumeMounts:
            - name: kedro-base-credentials
              readOnly: true
              mountPath: /tmp/kedro-base-credentials
            - name: kedro-env-credentials
              mountPath: /tmp/kedro-env-credentials
            - name: kedro-s3-paths
              mountPath: /tmp/kedro-s3-paths
              readOnly: true
          command:
            - /bin/bash
            - "-c"
            - |
                date;
                mkdir -p /hmda-etl-pipeline/conf/${KEDRO_ENV}/catalogs;
                cp /tmp/dev_postgres.yaml /hmda-etl-pipeline/conf/${KEDRO_ENV}/catalogs/;
                chmod -R 755 /hmda-etl-pipeline/conf/${KEDRO_ENV};

                echo "Building base credentials..."
                cat <<EOF > /hmda-etl-pipeline/conf/base/credentials.yaml
                production_pg_readonly:
                  con: "$(cat /tmp/kedro-base-credentials/production_pg_readonly)"

                hmda-kedro-test-bucket:
                client_kwargs:
                  region_name: "$(cat /tmp/kedro-base-credentials/hmda_kedro_test_bucket)"
                EOF

                echo "Building env credentials..."
                cat << EOF > /hmda-etl-pipeline/conf/${KEDRO_ENV}/credentials.yaml
                ${KEDRO_ENV}_pg_readonly:
                  con: "$(cat /tmp/kedro-env-credentials/${KEDRO_ENV}_pg_readonly)"
                EOF

                echo "Building globals..."
                cat << EOF > /hmda-etl-pipeline/conf/${KEDRO_ENV}/globals.yml
                regulator_path_prefix: "$(cat /tmp/kedro-s3-paths/regulator_path_prefix)"
                archive_public_path_prefix: "$(cat /tmp/kedro-s3-paths/archive_public_path_prefix)"
                public_path_prefix: "$(cat /tmp/kedro-s3-paths/public_path_prefix)"
                reports_path_prefix: "$(cat /tmp/kedro-s3-paths/reports_path_prefix)"
                credentials: "$(cat /tmp/kedro-s3-paths/credentials)"
                EOF

                cat /hmda-etl-pipeline/conf/${KEDRO_ENV}/catalogs/dev_postgres.yaml;
                mkdir -p /hmda-etl-pipeline/logs && touch /hmda-etl-pipeline/logs/info.log;

                cd /hmda-etl-pipeline/
                kedro run --runner=ThreadRunner --params="max_workers=2" --tags="2025_Filing_Season" --env=dev --to-outputs="reduced_lar_reports_parquet_2025";

                true; sleep 5
          resources:
            requests:
              memory: "3Gi"
              cpu: "1"
            limits:
              memory: "120Gi"
              cpu: "12"
      volumes:
        - name: kedro-base-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kedro-base-creds-spc
        - name: kedro-env-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kedro-env-creds-spc
        - name: kedro-s3-paths
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kedro-s3-paths-spc
        - name: kedro-dev-postgres-2025-yaml-configmap
          configMap:
            name: kedro-dev-postgres-2025-yaml-configmap
      tolerations:
        - key: node-group
          operator: Equal
          value: kedro-regular
      restartPolicy: OnFailure
      serviceAccountName: hmda-platform